name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint --module-rgx=all \
        --const-rgx=all \
        --class-rgx=all \
        --function-rgx=all \
        --method-rgx=all \ 
        --attr-rgx=all \
        --argument-rgx=all \
        --variable-rgx=all \
        --class-attribute-rgx=all \
        --class-const-rgx=all \
        --inlinevar-rgx=all \
        --typevar-rgx=all \
        $(git ls-files '*.py')
